CREATE TABLE book
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    isbn_10   VARCHAR(10),
    isbn_13   VARCHAR(13),
    title     VARCHAR(255),
    author    VARCHAR(255),
    thumbnail VARCHAR(255),
    CONSTRAINT pk_book PRIMARY KEY (id)
);

CREATE TABLE books_collection
(
    books_id      BIGINT NOT NULL,
    collection_id BIGINT NOT NULL,
    CONSTRAINT pk_books_collection PRIMARY KEY (books_id, collection_id)
);

CREATE TABLE collection
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    VARCHAR(255)                            NOT NULL,
    user_id VARCHAR(255),
    CONSTRAINT pk_collection PRIMARY KEY (id)
);

ALTER TABLE books_collection
    ADD CONSTRAINT fk_boocol_on_book FOREIGN KEY (books_id) REFERENCES book (id);

CREATE INDEX idx_books_collection_books_id ON books_collection (books_id);

ALTER TABLE books_collection
    ADD CONSTRAINT fk_boocol_on_collection FOREIGN KEY (collection_id) REFERENCES collection (id);

CREATE INDEX idx_books_collection_collection_id ON books_collection (collection_id);
