version: "3.1"

services:
  api:
    image: "augmart/book-recommendations-api"
    hostname: api
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - DB_URL=$DB_URL
      - DB_USERNAME=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
      - GOOGLE_BOOKS_API_KEY=$GOOGLE_BOOKS_API_KEY
      - NYTIMES_API_KEY=$NYTIMES_API_KEY
      - AUTH0_AUDIENCE=$AUTH0_AUDIENCE
      - AUTH0_ISSUER_URI=$AUTH0_ISSUER_URI


  client:
    image: "augmart/book-recommendations-frontend"
    depends_on:
      - api
    hostname: client
    ports:
      - "80:80"


