version: "3.1"

services:
  api:
    image: "augmart/book-recommendations-api"
    hostname: api
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - DB_URL=$DB_URL
      - DB_USERNAME=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
      - GOOGLE_BOOKS_API_KEY=$GOOGLE_BOOKS_API_KEY
      - NYTIMES_API_KEY=$NYTIMES_API_KEY

  client:
    image: "augmart/book-recommendations-frontend"
    hostname: client
    ports:
      - "3000:3000"


