version: "3.1"

services:
  api:
    image: "augmart/book-recommendations-api"
    hostname: api
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - DB_URL=$DB_URL
      - DB_USERNAME=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
      - GOOGLE_BOOKS_API_KEY=$GOOGLE_BOOKS_API_KEY
      - NYTIMES_API_KEY=$NYTIMES_API_KEY
      - AUTH0_AUDIENCE=$AUTH0_AUDIENCE
      - AUTH0_ISSUER_URI=$AUTH0_ISSUER_URI
      - CLIENT_SECRET=$CLIENT_SECRET
      - CLIENT_ID=$CLIENT_ID
      - AWS_CAMPAIGN_ARN=$AWS_CAMPAIGN_ARN
      - AWS_REGION=$AWS_REGION
      - AWS_IS_ENABLED=$AWS_IS_ENABLED
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY

  client:
    image: "augmart/book-recommendations-frontend"
    depends_on:
      - api
    hostname: client
    ports:
      - "80:80"


