name: Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "**" ]


permissions:
  contents: read

jobs:
  publish-to-docker:
    needs: [build-spring, build-vue]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push spring image
        uses: docker/build-push-action@v3
        with:
            context: ./book-recommendations
            push: true
            tags: augmart/book-recommendations-api
      - name: Build and push vue image
        uses: docker/build-push-action@v3
        with:
            context: ./book-recommendations/frontend
            push: true
            tags: augmart/book-recommendations-frontend
